### ISSUE TITLE
error in index.js

### ISSUE THREAD

**Issue by davidroberto** [whmountains/gulp-atomizer#6] opened 2016-07-22 17:55 UTC
Hello,

There is a small mistake in your index.js, line 80, which crash the execution.

var cssOut = options ? acss.getCss(finalConfig, options) : ascc.getCss(finalConfig)

ascc.getCss(finalConfig) should be acss.getCss(finalConfig)

Anyway, thanks a lot for this module :) 

David

**Comment by fidian** [comment] 2016-08-10 02:42
I might be missing the problem, but I do not see the issue that you are reporting.  Maybe it got fixed?  Is this issue still relevant?

**Comment by fidian** [comment] 2016-08-10 14:14
Sorry, I was totally wrong.  It's there.

There is a workaround.  Just make sure to pass an empty options object.

```
acss = require("gulp-atomizer");
conf = require("atomizer-config.json");
gulp.src("./*.html")
    .pipe(acss("atomic.css", conf, {}))
    .pipe(gulp.dest("./"))
```

The magic `{}` on the line where `acss()` is called will do the trick until the maintainer fixes this typo.

**Comment by fidian** [comment] 2016-08-10 14:21
Ok, I think I understand now.  I first looked at the GitHub repository and the issue is fixed there.

Next, I looked at the installed module in a project and saw the problem.

The real solution to this is to publish the node module again.  It's fixed in the source but the version on npm has the error.

**Comment by davidroberto** [comment] 2016-08-10 16:42
Ok Thanks for the update :)

**Comment by fidian** [comment] 2016-09-02 12:45
A new version was not [published](https://www.npmjs.com/package/gulp-atomizer).  I also tried to install it again from npm to a fresh repository and this problem still exists.  Why was this ticket closed?

**Comment by KevinLandsberg** [comment] 2016-10-27 14:42
Hi guys,

i am getting the same error in my terminal when i do a npm install of the gulp-atomizer.
There is a typo error in line 80, instead of 'ascc' you should call it 'acss'.
The index.js on github looks fine, you should publish your github repository on npm maybe, so we can have a fixed index.js when we do a npm install for getting the gulp-atomizer.
Thank you,

greetings Kevin.

**Comment by whmountains** [comment] 2016-10-27 15:38
Sorry Kevin.  I guess I let it slip.  I’ll try to get it published 
this evening!

Caleb

**Comment by KevinLandsberg** [comment] 2016-11-03 13:44
Thank you!

**Comment by fidian** [comment] 2016-11-03 18:05
@whmountains Any chance this could get published?

**Comment by whmountains** [comment] 2016-11-03 21:45
Published.

**Comment by whmountains** [comment] 2016-11-03 21:57
I just want to apologize to everyone who has come here and found this not working.  I'll try to stay more on top of this.

As an extra measure to prevent it from happening again, I'm going to add @absentsemicolon as a  maintainer so there will be a second person in case I'm not around.

**Closed as completed** 2016-11-03 21:57 UTC

**Comment by KevinLandsberg** [comment] 2016-11-08 08:39
Thank you for your effort!
